export const STR_TXT = {
  back: 'Back',
  capital: 'Capital',
  population: 'Population',
  region: 'Region',
  empty: 'I sorry, I didn´t find anything',
  titleHeader: 'Where in the world?',
  mode: 'Mode',
  borderCountries: 'Border Countries:',
  nativeName: 'Native Name',
  subRegion: 'Sub Region',
  topLevelDomain: 'Top Level Domain',
  currencies: 'Currencies',
  languages: 'Languages',
  classNamePrefix: 'customSelect',
  filterByRegion: 'Filter by Region',
  search: 'search',
  SearchCountry: 'Search for a country...',
  all: 'All',
  oops: 'Oops!!!',
  sorry: 'Sorry, an unexpected error has occurred.',
  titleError: 'Message Error',
};
